### ISSUE TITLE
After the update 3.0.3, homey can no longer reach my Nefit Easy

### ISSUE THREAD

**Issue by Bhitv** [robertklep/nl.nefit.easy#1]
After the update 3.0.3, homey can no longer reach my Nefit Easy.
I have made no changes and the settings are correct according to Nefit Easy

Bas

**Comment by robertklep** [comment]
Which version were you running before? 3.0.2 was the last stable I believe, and the changes between 3.0.2 and 3.0.3 are minor (and not code-related), and 3.0.3 runs okay on my Homey.

Are you getting an error when you hover over the device entry?

**Comment by Bhitv** [comment]
Sorry Robert
It took some time, after the update, but homey now sees him again.
Thank you for your response and commitment.

Bas

**Comment by robertklep** [comment]
No worries, glad the problem solved itself! 😎
