### ISSUE TITLE
vakantieprogramma not working with homey flow

### ISSUE THREAD

**Issue by JohanKrab** [robertklep/nl.nefit.easy#1]
When set the ¨vakantieprogramma¨ via a flow it is set but after a few seconds it unset itself after a few seconds.

**Comment by robertklep** [comment]
What does the official Nefit app show in that case? Does it show that you changed to the holiday program, and does it change back as well?

I don't have a Nefit Easy anymore so can't test myself.

**Comment by D117D** [comment]
The same problem here. The app indicates that the holiday program has been activated and after a few seconds it switches back to the clock program. This means that the Nefit constantly makes hot tap water during the holiday.

Example of the app:
![IMG_6090](https://github.com/user-attachments/assets/91f59dae-4821-4351-83af-226864c193f6)
After a few seconds:
![IMG_6091](https://github.com/user-attachments/assets/f01e4698-52c1-4196-aaa6-4be4fdb9ad65)

In the app you normally have to provide additional data. See the example:
![IMG_6092](https://github.com/user-attachments/assets/692daaf7-fed1-4b42-8af6-2b0e627ed7d3)

**Comment by robertklep** [comment]
I guess the missing additional data is causing the Easy to revert back to the non-holiday program.

Like I said, I don't have an Easy anymore so I can't fix this 😔
