### ISSUE TITLE
Problem “hot water” and “central heating”

### ISSUE THREAD

**Issue by MichaelHendriks** [robertklep/nl.nefit.easy#17]
When the “central heating” is on and you use “hot water”, “hot water” don’t switch to on.

**Comment by MichaelHendriks** [comment]
Practical “central heating” is warming the house and stops when you need “hot water”. The “central heating” starts again when the “hot water” stops.

**Comment by robertklep** [comment]
It may take up to a minute until the value gets updated. Have you waited that long?

**Comment by robertklep** [comment]
Yes, it is. The default is 60 seconds, but you can lower it to 30 seconds.

**Comment by MichaelHendriks** [comment]
![8FA3A5F4-2D82-4D38-8C32-5E51F6ED3CD6](https://user-images.githubusercontent.com/55698537/67929426-96dd7f80-fbbd-11e9-8c23-4d37f94f1e87.jpeg)

**Comment by MichaelHendriks** [comment]
I took “hot water” for 2 minutes when the “central heating” was heated. But nothing changed.

**Comment by MichaelHendriks** [comment]
It seems that I have a problem with the control of my Nefit Easy Connect module.
This translates the control of the OpenTherm to Nefit Easy thermostat.

**Comment by robertklep** [comment]
I assume though that when you turn on hot water, that state will be reflected on the Easy itself?

**Comment by MichaelHendriks** [comment]
Yes, the Nefit Easy shows only “the flame” and don’t changed.
I will inform Nefit about this.

**Comment by robertklep** [comment]
Thanks 👍🏻

I'll close this issue for now.
