### ISSUE TITLE
max_retries_reached

### ISSUE THREAD

**Issue by ronald2404** [robertklep/nl.nefit.easy#2]
Hi Robert,

i am getting the max_retries_reached error in homey. 
Ik gebruik de laatste officiele versie van je ap..

twee weken terug had ik dit ook toen heb ik de nefit verwijderd en toegevoegd. Maar moest dus ook mijn flows weer aanpasssen.

De nefit easy is wel te bereiken via de nefit app.

groeten

Ronald

**Comment by robertklep** [comment]
Ik heb zojuist de beta versie (v3.2.0) als "stable" gemarkeerd. Die draai ik zelf al bijna anderhalve maand probleemloos.

De oudere v3 versies zijn gebaseerd op een nieuwe onderliggende library die voor behoorlijk wat problemen heeft gezorgd, dus bij v3.2.0 heb ik die weer vervangen.

**Comment by ronald2404** [comment]
Okay thanks ga ik die installeren!

**Comment by ronald2404** [comment]
Zojuist gelijk gedaan en hij doet het weer! Dankjewel
