### ISSUE TITLE
"Stel de modus in" is useless

### ISSUE THREAD

**Issue by robertklep** [robertklep/nl.nefit.easy#3]
<s>The `thermostat_mode` capability isn't very useful in flow actions. Instead, it makes more sense to use `clock_programme` to switch between clock mode and manual mode.</s>

Added in 6b097f8915899063851a0fac52cc84e662300def

**Comment by erikrood** [comment]
I agree there; would it then also possible to activate the fireplace programme? That is a pretty unique function which would nice to be controlled by Homey. 
A usecase could be that if the temperature is much higher as the programmed temperature  then the fireplace could be heating up the place and the fireplace mode could then be switched on

**Comment by robertklep** [comment]
Good point, I'll look into that as well.

**Comment by robertklep** [comment]
@erikrood regarding the fireplace mode: I have a choice to add it as a "custom capability", or only as a flow action/condition.

Adding it as a capability has the advantage that the current state of the fireplace mode will be shown in the "mobile card". However, the big downside is that it isn't possible to add new capabilities to an existing Homey device, which means that before you can get it working properly, you have to re-pair the Nefit Easy (which also means fixing all your flows that use it).

Adding it purely as a flow action/condition doesn't have that downside, but the downside there is that it's isn't possible to show the current state of the fireplace mode on Homey.

Do you have a preference for one over the other? I'm not yet sure which one has my own preference.

**Comment by erikrood** [comment]
Thank you.

**Comment by robertklep** [comment]
@erikrood so do you have a preference? 😁

**Comment by erikrood** [comment]
Sorry, I see that most of my comments did not get in the answer, so hereby new
 
I would suggest adding this as a capability as this will be a one-off action and would give the user confidence in that his flow works. The Nefit display does not show the fireplace function on the screen so there is no other easy proof that the function is working.  
Would it by this method also show and be capable to switch to the other temp overwrite states?
That would build the case for the capability as some of them would overwrite each other.
A usecase where the magister functionality will determine if there is a need for a family member to go to school and switch the heating to 'Today as sunday'  should not overwrite the fireplace function.
This can then be checked in the mobile capability (for programming reasons)

With regards to the current users; I would expect that not too many users will have build it in the flows (maybe as a quick way to get the outside temperature )

Hope that this makes sense, happy to bring in more input or thoughts

**Comment by robertklep** [comment]
@erikrood thanks for the feedback!

The cleanest solution, going forward, would be to add a new capability, so I'll do that. I have a few flows that are based on the Nefit Easy myself, like notifying me when the system pressure is too high or too low, but those are easy to re-create.

As for "other temp overwrite states", which ones do you mean? Programme vs manual mode is already a separate capability.

**Comment by robertklep** [comment]
Sneak preview of the new "fireplace mode" capability:

![image](https://user-images.githubusercontent.com/1190916/48711894-afeb5b80-ec0c-11e8-9436-1c6305d2b9d2.png)

**Comment by erikrood** [comment]
Nice! clear stylish  icon

**Comment by erikrood** [comment]
With regards to the overwrite I was referring to the other temp states next to programme or manual. 
There are four  temp overrides
Fireplace 
Holiday functie 
Today as sunday
Tomorrow as sunday
These settings work for a limted time. While the program and manual  continue until interrupted.
The temp ones are nice to control by homey as they will reset to the standard after some time.
The flows should be easy to setup. However making multiple flows setting  it to temp mode makes it easy to overwrite a holidaymode through a fireplacemode. The fireplace mode will reset itself back programme or manual when it is midnight.
Hope this explains my thoughts in more detail

**Comment by erikrood** [comment]
Hi Robert,
You are right, there can only be one status active at the time.
One basis which will can over written by one temp mode only
So one flowcard will do fine
The other (next to the fireplace) I expect to be date/time driven, maybe they are somehow driven by the time/date schema?

**Comment by robertklep** [comment]
Just published v3.3.0 (beta). It doesn't yet contain every feature I had hoped for, but at least the fireplace and holiday modes are now supported.

It depends on Athom how fast the beta will be available in the app store, might take a few days.

**Comment by erikrood** [comment]
Hi Robert, When available I will test this. Thanks for the effort

**Comment by robertklep** [comment]
v3.3.0 was just published.

**Comment by erikrood** [comment]
It installed without a problem and looks nice, I am now battling how to put my test case in a rule

**Comment by ferrydl** [comment]
Hi Robert (en Erik),

Thank you very much for quickly picking up my report about the modes. This
works very well. I can now switch the mode via the flow manager. Nice!

Greetings, Ferry

Op wo 28 nov. 2018 om 18:01 schreef Robert Klep <notifications@github.com>:

**Comment by robertklep** [comment]
Thanks for testing, everyone! I'm promoting the app to the stable channel 😄
