### ISSUE TITLE
Is this app ready for Homey 2.0?

### ISSUE THREAD

**Issue by FrankRinkens** [robertklep/nl.nefit.easy#8]
Is this app ready for Homey 2.0?

Because I installed the app on 2.0 RC version but how to add and configure the Nefit?

I tried:
   at Instellingen - Apps    => Nefit Easy is not in the list
   at meer - apps - Nefit Easy - Config  => no add/configure Nefit option

Br
Frank

**Comment by robertklep** [comment]
> Is this app ready for Homey 2.0?

I'm not on v2.0 myself, so I haven't worked on making it V2-ready. Sounds like it's not compatible.

**Comment by FrankRinkens** [comment]
It works on 2.0

**Comment by robertklep** [comment]
@FrankRinkens thanks for the feedback! Does that also include the "Instellingen"?

**Comment by FrankRinkens** [comment]
I just added the Nefit Easy as a new device and I can put in serienummer, toegangscode, wachtwoord. After that you can adjust temp, see outside temp and see pressure. I'm not using the hot water function.

**Comment by robertklep** [comment]
Sounds good, thanks for testing :)
