### ISSUE TITLE
Trying to send notification when operation mode or thermostaat status change

### ISSUE THREAD

**Issue by RonBartsch** [robertklep/nl.nefit.easy#9]
Since I upgraded to Homey 2.0, I don't receive any messages when operation mode or thermostaat changes status. I created a flow that when operation modus = CV it should sent me a notification to my mobile.

**Comment by RonBartsch** [comment]
Yes they are working.
I can see that the operation modus is CV in the app, and when I test the flow it looks like it doesn't recognize the status. Since the test flow give an error on the status.

**Comment by robertklep** [comment]
Can you see what the error is? Typically by hovering over the red triangle.

**Comment by RonBartsch** [comment]
Hehe, all I can see is the red triangle. No options to see details.

I'm testing a bit further, because a test flow with conditiion "when bedrijfsmodus is not CV" seems to be working. Buit doesn't get triggered normally.

**Comment by robertklep** [comment]
Is it possible to make a screenshot of the entire flow?

**Comment by RonBartsch** [comment]
No sorry I deleted that flow and went for something very basic to just sent me a notification when bedrijfsmodus changes.

That flow is working when I test the flow, but doesn't get triggered in normail situation.
The app for homey 2.0 doesn't give any logging options as far as I can see.
I'm searching if it's possible to see some logging of flows in homey 2.0.

**Comment by robertklep** [comment]
Since I'm not running v2 yet, I can't check myself, so I'm afraid it'll have to wait until I have installed v2.

**Comment by RonBartsch** [comment]
Ok no problem.
I can see in the device (homey app) what the status is CV / Off or Water, this changes correctly.

In the current version of the app and insights there seems to be no logging for the flows.

**Comment by itshows** [comment]
same here, flow test goes fine, but actual trigger doen not work.
if there is anything i can do, please let me know.

**Comment by robertklep** [comment]
It's not the first time I'm hearing about problems with flows on v2 :( I can't debug this until I'm on v2 myself.

**Comment by itshows** [comment]
ok i will wait for you to upgrade.
in the v2 testflight app with the old firmware everything worked ok.
it is the new v2 app with the v2 firmware wich gives problems

**Comment by itshows** [comment]
@robertklep 
a free developer homey would be nice for you ;)

**Comment by robertklep** [comment]
@itshows if everything worked as expected in the old v2 app, and it doesn't anymore, I'm going to make the bold statement that it's a problem with either the current v2 app, or Homey's core. I haven't changed anything in the app in the mean time.

@RonBartsch from that I know, the new insights can only be used for numerical capabilities, and operating mode isn't numerical. So I don't think that it will be possible to add it to insights (like like insights has lost the ability to graph boolean values).

**Comment by itshows** [comment]
last night homey update 2.0.1-rc2 has been installed and nefit easy app seems to be working again. I now get notifications when modus has changed.
![image](https://user-images.githubusercontent.com/46216331/51518420-16b00f80-1e1e-11e9-8a37-8d46b7f90592.png)
I will try the rest when i am at home.

**Comment by robertklep** [comment]
@itshows thanks for the update!

**Comment by RonBartsch** [comment]
yes I can confirm it's working now after the update.

**Comment by robertklep** [comment]
Thanks folks, closing this issue for now :)
